openapi: 3.0.0
info:
  title: Mi API Final
  version: 1.0.0
  description: API de ejemplo con Express, MongoDB, JWT y Swagger

servers:
  - url: http://localhost:4000

paths:
  /api/v1/hello:
    get:
      summary: Endpoint Hola Mundo
      responses:
        "200":
          description: Respuesta exitosa

  /api/v1/saludo/{nombre}:
    get:
      summary: Devuelve un saludo con el nombre
      parameters:
        - name: nombre
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Respuesta exitosa

  /api/v1/login:
    post:
      summary: Login de usuario, devuelve un JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Token JWT generado

  /api/v1/usuarios:
    get:
      summary: Lista de usuarios (requiere JWT)
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de usuarios

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
